version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    reviewers:
      - "patrikkarlsson72"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] 